use codec::{Decode, Encode};
use polymesh_dart::{
    MediatorAffirmationProof as NativeMediatorAffirmationProof,
    ReceiverAffirmationProof as NativeReceiverAffirmationProof,
    ReceiverClaimProof as NativeReceiverClaimProof,
    SenderAffirmationProof as NativeSenderAffirmationProof,
    SenderCounterUpdateProof as NativeSenderCounterUpdateProof,
    SenderReversalProof as NativeSenderReversalProof,
};
use wasm_bindgen::prelude::*;

/// Zero-knowledge proof that the sender affirms a settlement leg.
///
/// This proof is generated by the sender to affirm their participation in a settlement leg,
/// proving they have sufficient balance without revealing the actual amount or balance.
/// The proof is submitted on-chain via the `senderAffirmation` transaction.
///
/// # Example
/// ```javascript
/// // Generate sender affirmation proof
/// const proof = issuerAccountState.senderAffirmProof(
///   issuerKeys,
///   accountPath,
///   settlementRef,
///   legId,
///   encryptedLeg,
///   assetId,
///   amount
/// );
///
/// // Submit the affirmation
/// const result = await issuer.senderAffirmation(proof);
/// ```
#[wasm_bindgen]
pub struct SenderAffirmationProof {
    pub(crate) inner: NativeSenderAffirmationProof,
}

#[wasm_bindgen]
impl SenderAffirmationProof {
    /// Exports the proof as a SCALE-encoded byte array.
    ///
    /// This is useful for storing or transmitting the proof in a compact binary format.
    ///
    /// # Returns
    /// A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const bytes = proof.toBytes();
    /// // Store or transmit bytes
    /// ```
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.inner.encode()
    }

    /// Imports a proof from a SCALE-encoded byte array.
    ///
    /// # Arguments
    /// * `bytes` - A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Returns
    /// A `SenderAffirmationProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the bytes are not a valid SCALE-encoded sender affirmation proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = SenderAffirmationProof.fromBytes(bytes);
    /// ```
    #[wasm_bindgen(js_name = fromBytes)]
    pub fn from_bytes(bytes: &[u8]) -> Result<SenderAffirmationProof, JsValue> {
        let inner = NativeSenderAffirmationProof::decode(&mut &bytes[..]).map_err(|e| {
            JsValue::from_str(&format!("Failed to decode sender affirmation proof: {}", e))
        })?;
        Ok(SenderAffirmationProof { inner })
    }

    /// Exports the proof as a hex-encoded string.
    ///
    /// # Returns
    /// A hex string (without "0x" prefix) representing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const hexString = proof.toHex();
    /// console.log(hexString); // "a1b2c3..."
    /// ```
    #[wasm_bindgen(js_name = toHex)]
    pub fn to_hex(&self) -> String {
        hex::encode(self.to_bytes())
    }

    /// Imports a proof from a hex-encoded string.
    ///
    /// # Arguments
    /// * `hex_str` - A hex string representing the SCALE-encoded proof (with or without "0x" prefix).
    ///
    /// # Returns
    /// A `SenderAffirmationProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the string is not valid hex.
    /// * Throws an error if the decoded bytes are not a valid sender affirmation proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = SenderAffirmationProof.fromHex("a1b2c3...");
    /// // or with 0x prefix
    /// const proof2 = SenderAffirmationProof.fromHex("0xa1b2c3...");
    /// ```
    #[wasm_bindgen(js_name = fromHex)]
    pub fn from_hex(hex_str: &str) -> Result<SenderAffirmationProof, JsValue> {
        let bytes = hex::decode(hex_str)
            .map_err(|e| JsValue::from_str(&format!("Invalid hex string: {}", e)))?;
        Self::from_bytes(&bytes)
    }
}

/// Zero-knowledge proof that the receiver affirms a settlement leg.
///
/// This proof is generated by the receiver to affirm their participation in a settlement leg.
/// After the receiver affirms, they can later claim the transferred assets.
/// The proof is submitted on-chain via the `receiverAffirmation` transaction.
///
/// # Example
/// ```javascript
/// // Generate receiver affirmation proof
/// const proof = investorAccountState.receiverAffirmProof(
///   investorKeys,
///   accountPath,
///   settlementRef,
///   legId,
///   encryptedLeg,
///   assetId,
///   amount
/// );
///
/// // Submit the affirmation
/// const result = await investor.receiverAffirmation(proof);
/// ```
#[wasm_bindgen]
pub struct ReceiverAffirmationProof {
    pub(crate) inner: NativeReceiverAffirmationProof,
}

#[wasm_bindgen]
impl ReceiverAffirmationProof {
    /// Exports the proof as a SCALE-encoded byte array.
    ///
    /// # Returns
    /// A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const bytes = proof.toBytes();
    /// ```
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.inner.encode()
    }

    /// Imports a proof from a SCALE-encoded byte array.
    ///
    /// # Arguments
    /// * `bytes` - A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Returns
    /// A `ReceiverAffirmationProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the bytes are not a valid SCALE-encoded receiver affirmation proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = ReceiverAffirmationProof.fromBytes(bytes);
    /// ```
    #[wasm_bindgen(js_name = fromBytes)]
    pub fn from_bytes(bytes: &[u8]) -> Result<ReceiverAffirmationProof, JsValue> {
        let inner = NativeReceiverAffirmationProof::decode(&mut &bytes[..]).map_err(|e| {
            JsValue::from_str(&format!(
                "Failed to decode receiver affirmation proof: {}",
                e
            ))
        })?;
        Ok(ReceiverAffirmationProof { inner })
    }

    /// Exports the proof as a hex-encoded string.
    ///
    /// # Returns
    /// A hex string (without "0x" prefix) representing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const hexString = proof.toHex();
    /// ```
    #[wasm_bindgen(js_name = toHex)]
    pub fn to_hex(&self) -> String {
        hex::encode(self.to_bytes())
    }

    /// Imports a proof from a hex-encoded string.
    ///
    /// # Arguments
    /// * `hex_str` - A hex string representing the SCALE-encoded proof (with or without "0x" prefix).
    ///
    /// # Returns
    /// A `ReceiverAffirmationProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the string is not valid hex.
    /// * Throws an error if the decoded bytes are not a valid receiver affirmation proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = ReceiverAffirmationProof.fromHex("a1b2c3...");
    /// ```
    #[wasm_bindgen(js_name = fromHex)]
    pub fn from_hex(hex_str: &str) -> Result<ReceiverAffirmationProof, JsValue> {
        let bytes = hex::decode(hex_str)
            .map_err(|e| JsValue::from_str(&format!("Invalid hex string: {}", e)))?;
        Self::from_bytes(&bytes)
    }
}

/// Zero-knowledge proof for claiming assets from a settlement leg.
///
/// After a settlement leg has been affirmed by both sender and receiver, the receiver
/// generates this proof to claim the transferred assets. This updates the receiver's
/// on-chain balance commitment. The proof is submitted via the `receiverClaim` transaction.
///
/// # Example
/// ```javascript
/// // Generate claim proof
/// const proof = investorAccountState.receiverClaimProof(
///   investorKeys,
///   accountPath,
///   settlementRef,
///   legId,
///   encryptedLeg,
///   assetId,
///   amount
/// );
///
/// // Submit the claim
/// const result = await investor.receiverClaim(proof);
/// ```
#[wasm_bindgen]
pub struct ReceiverClaimProof {
    pub(crate) inner: NativeReceiverClaimProof,
}

#[wasm_bindgen]
impl ReceiverClaimProof {
    /// Exports the proof as a SCALE-encoded byte array.
    ///
    /// # Returns
    /// A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const bytes = proof.toBytes();
    /// ```
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.inner.encode()
    }

    /// Imports a proof from a SCALE-encoded byte array.
    ///
    /// # Arguments
    /// * `bytes` - A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Returns
    /// A `ReceiverClaimProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the bytes are not a valid SCALE-encoded receiver claim proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = ReceiverClaimProof.fromBytes(bytes);
    /// ```
    #[wasm_bindgen(js_name = fromBytes)]
    pub fn from_bytes(bytes: &[u8]) -> Result<ReceiverClaimProof, JsValue> {
        let inner = NativeReceiverClaimProof::decode(&mut &bytes[..]).map_err(|e| {
            JsValue::from_str(&format!("Failed to decode receiver claim proof: {}", e))
        })?;
        Ok(ReceiverClaimProof { inner })
    }

    /// Exports the proof as a hex-encoded string.
    ///
    /// # Returns
    /// A hex string (without "0x" prefix) representing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const hexString = proof.toHex();
    /// ```
    #[wasm_bindgen(js_name = toHex)]
    pub fn to_hex(&self) -> String {
        hex::encode(self.to_bytes())
    }

    /// Imports a proof from a hex-encoded string.
    ///
    /// # Arguments
    /// * `hex_str` - A hex string representing the SCALE-encoded proof (with or without "0x" prefix).
    ///
    /// # Returns
    /// A `ReceiverClaimProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the string is not valid hex.
    /// * Throws an error if the decoded bytes are not a valid receiver claim proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = ReceiverClaimProof.fromHex("a1b2c3...");
    /// ```
    #[wasm_bindgen(js_name = fromHex)]
    pub fn from_hex(hex_str: &str) -> Result<ReceiverClaimProof, JsValue> {
        let bytes = hex::decode(hex_str)
            .map_err(|e| JsValue::from_str(&format!("Invalid hex string: {}", e)))?;
        Self::from_bytes(&bytes)
    }
}

/// Zero-knowledge proof for updating the sender's counter after leg affirmation.
///
/// After the sender has affirmed a settlement leg, they may need to update their counter
/// if there are changes to the settlement. This proof allows updating the counter without
/// revealing sensitive information. Submitted via the `senderCounterUpdate` transaction.
///
/// # Example
/// ```javascript
/// // Generate counter update proof
/// const proof = issuerAccountState.senderCounterUpdateProof(
///   issuerKeys,
///   accountPath,
///   settlementRef,
///   legId,
///   encryptedLeg,
///   assetId,
///   amount
/// );
///
/// // Submit the counter update
/// const result = await issuer.senderCounterUpdate(proof);
/// ```
#[wasm_bindgen]
pub struct SenderCounterUpdateProof {
    pub(crate) inner: NativeSenderCounterUpdateProof,
}

#[wasm_bindgen]
impl SenderCounterUpdateProof {
    /// Exports the proof as a SCALE-encoded byte array.
    ///
    /// # Returns
    /// A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const bytes = proof.toBytes();
    /// ```
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.inner.encode()
    }

    /// Imports a proof from a SCALE-encoded byte array.
    ///
    /// # Arguments
    /// * `bytes` - A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Returns
    /// A `SenderCounterUpdateProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the bytes are not a valid SCALE-encoded sender counter update proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = SenderCounterUpdateProof.fromBytes(bytes);
    /// ```
    #[wasm_bindgen(js_name = fromBytes)]
    pub fn from_bytes(bytes: &[u8]) -> Result<SenderCounterUpdateProof, JsValue> {
        let inner = NativeSenderCounterUpdateProof::decode(&mut &bytes[..]).map_err(|e| {
            JsValue::from_str(&format!(
                "Failed to decode sender counter update proof: {}",
                e
            ))
        })?;
        Ok(SenderCounterUpdateProof { inner })
    }

    /// Exports the proof as a hex-encoded string.
    ///
    /// # Returns
    /// A hex string (without "0x" prefix) representing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const hexString = proof.toHex();
    /// ```
    #[wasm_bindgen(js_name = toHex)]
    pub fn to_hex(&self) -> String {
        hex::encode(self.to_bytes())
    }

    /// Imports a proof from a hex-encoded string.
    ///
    /// # Arguments
    /// * `hex_str` - A hex string representing the SCALE-encoded proof (with or without "0x" prefix).
    ///
    /// # Returns
    /// A `SenderCounterUpdateProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the string is not valid hex.
    /// * Throws an error if the decoded bytes are not a valid sender counter update proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = SenderCounterUpdateProof.fromHex("a1b2c3...");
    /// ```
    #[wasm_bindgen(js_name = fromHex)]
    pub fn from_hex(hex_str: &str) -> Result<SenderCounterUpdateProof, JsValue> {
        let bytes = hex::decode(hex_str)
            .map_err(|e| JsValue::from_str(&format!("Invalid hex string: {}", e)))?;
        Self::from_bytes(&bytes)
    }
}

/// Zero-knowledge proof for reversing a sender's affirmation of a settlement leg.
///
/// If the sender needs to cancel their affirmation before the settlement executes,
/// they generate this proof to revert their affirmed state. This restores their balance
/// commitment as if the affirmation never happened. Submitted via the `senderRevert` transaction.
///
/// # Example
/// ```javascript
/// // Generate reversal proof
/// const proof = issuerAccountState.senderRevertProof(
///   issuerKeys,
///   accountPath,
///   settlementRef,
///   legId,
///   encryptedLeg,
///   assetId,
///   amount
/// );
///
/// // Submit the reversal
/// const result = await issuer.senderRevert(proof);
/// ```
#[wasm_bindgen]
pub struct SenderReversalProof {
    pub(crate) inner: NativeSenderReversalProof,
}

#[wasm_bindgen]
impl SenderReversalProof {
    /// Exports the proof as a SCALE-encoded byte array.
    ///
    /// # Returns
    /// A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const bytes = proof.toBytes();
    /// ```
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.inner.encode()
    }

    /// Imports a proof from a SCALE-encoded byte array.
    ///
    /// # Arguments
    /// * `bytes` - A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Returns
    /// A `SenderReversalProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the bytes are not a valid SCALE-encoded sender reversal proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = SenderReversalProof.fromBytes(bytes);
    /// ```
    #[wasm_bindgen(js_name = fromBytes)]
    pub fn from_bytes(bytes: &[u8]) -> Result<SenderReversalProof, JsValue> {
        let inner = NativeSenderReversalProof::decode(&mut &bytes[..]).map_err(|e| {
            JsValue::from_str(&format!("Failed to decode sender reversal proof: {}", e))
        })?;
        Ok(SenderReversalProof { inner })
    }

    /// Exports the proof as a hex-encoded string.
    ///
    /// # Returns
    /// A hex string (without "0x" prefix) representing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const hexString = proof.toHex();
    /// ```
    #[wasm_bindgen(js_name = toHex)]
    pub fn to_hex(&self) -> String {
        hex::encode(self.to_bytes())
    }

    /// Imports a proof from a hex-encoded string.
    ///
    /// # Arguments
    /// * `hex_str` - A hex string representing the SCALE-encoded proof (with or without "0x" prefix).
    ///
    /// # Returns
    /// A `SenderReversalProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the string is not valid hex.
    /// * Throws an error if the decoded bytes are not a valid sender reversal proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = SenderReversalProof.fromHex("a1b2c3...");
    /// ```
    #[wasm_bindgen(js_name = fromHex)]
    pub fn from_hex(hex_str: &str) -> Result<SenderReversalProof, JsValue> {
        let bytes = hex::decode(hex_str)
            .map_err(|e| JsValue::from_str(&format!("Invalid hex string: {}", e)))?;
        Self::from_bytes(&bytes)
    }
}

/// Zero-knowledge proof for mediator affirmation of a settlement.
///
/// Mediators (also called auditors) are special parties that can observe and validate
/// confidential settlements. They generate this proof to affirm a settlement using their
/// encryption keys. This allows them to audit the settlement without blocking it.
///
/// # Example
/// ```javascript
/// // Decrypt and verify the settlement leg as mediator
/// const decryptedLeg = encryptedLeg.decrypt(mediatorEncryptionKey);
///
/// // Mediator generates affirmation proof (implementation dependent on use case)
/// const proof = ...; // Generated through mediator-specific flow
///
/// // Submit the affirmation
/// const result = await mediator.mediatorAffirmation(proof);
/// ```
#[wasm_bindgen]
pub struct MediatorAffirmationProof {
    pub(crate) inner: NativeMediatorAffirmationProof,
}

#[wasm_bindgen]
impl MediatorAffirmationProof {
    /// Exports the proof as a SCALE-encoded byte array.
    ///
    /// # Returns
    /// A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const bytes = proof.toBytes();
    /// ```
    #[wasm_bindgen(js_name = toBytes)]
    pub fn to_bytes(&self) -> Vec<u8> {
        self.inner.encode()
    }

    /// Imports a proof from a SCALE-encoded byte array.
    ///
    /// # Arguments
    /// * `bytes` - A `Uint8Array` containing the SCALE-encoded proof.
    ///
    /// # Returns
    /// A `MediatorAffirmationProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the bytes are not a valid SCALE-encoded mediator affirmation proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = MediatorAffirmationProof.fromBytes(bytes);
    /// ```
    #[wasm_bindgen(js_name = fromBytes)]
    pub fn from_bytes(bytes: &[u8]) -> Result<MediatorAffirmationProof, JsValue> {
        let inner = NativeMediatorAffirmationProof::decode(&mut &bytes[..]).map_err(|e| {
            JsValue::from_str(&format!(
                "Failed to decode mediator affirmation proof: {}",
                e
            ))
        })?;
        Ok(MediatorAffirmationProof { inner })
    }

    /// Exports the proof as a hex-encoded string.
    ///
    /// # Returns
    /// A hex string (without "0x" prefix) representing the SCALE-encoded proof.
    ///
    /// # Example
    /// ```javascript
    /// const hexString = proof.toHex();
    /// ```
    #[wasm_bindgen(js_name = toHex)]
    pub fn to_hex(&self) -> String {
        hex::encode(self.to_bytes())
    }

    /// Imports a proof from a hex-encoded string.
    ///
    /// # Arguments
    /// * `hex_str` - A hex string representing the SCALE-encoded proof (with or without "0x" prefix).
    ///
    /// # Returns
    /// A `MediatorAffirmationProof` instance.
    ///
    /// # Errors
    /// * Throws an error if the string is not valid hex.
    /// * Throws an error if the decoded bytes are not a valid mediator affirmation proof.
    ///
    /// # Example
    /// ```javascript
    /// const proof = MediatorAffirmationProof.fromHex("a1b2c3...");
    /// ```
    #[wasm_bindgen(js_name = fromHex)]
    pub fn from_hex(hex_str: &str) -> Result<MediatorAffirmationProof, JsValue> {
        let bytes = hex::decode(hex_str)
            .map_err(|e| JsValue::from_str(&format!("Invalid hex string: {}", e)))?;
        Self::from_bytes(&bytes)
    }
}
